### ISSUE TITLE
[BUG] Metpy-Dask Integration to Calculate Wetbulb Temperature 

### ISSUE THREAD

**Issue by lennijusten** [xgcm/xgcm#289]
Hello,
I'm using Dask to chunk xarrays and pass them into the `metpy.calc.wet_bulb_temperature` function and am getting a cryptic error message that I believe is due to something breaking internally in the wetbulb function. I understand from Unidata/MetPy#1479 that Dask integration is an ongoing project, so this is more of an error documentation than request for an immediate fix. 

```
import metpy.calc
import xarray as xr

# Setup adaptive dask client
cluster = LocalCluster(dashboard_address=':8901',memory_limit='5GB',threads_per_worker=1 )
cluster.adapt(minimum=1, maximum=10)  # scale between 0 and 10 workers
client=Client(cluster)

# Load pressure, temperature, and water vapor mixing ratio
def init_data(chunks_dict):
    ds_press = xr.open_dataset('cesmLE1/atm/proc/tseries/monthly/PS/b.e11.B20TRC5CNBDRD.f09_g16.001.cam.h0.PS.185001-200512.nc', chunks=chunks_dict)
    ds_temp = xr.open_dataset('cesmLE1/atm/proc/tseries/daily/TREFHT/b.e11.BRCP85C5CNBDRD.f09_g16.001.cam.h1.TREFHT.20810101-21001231.nc', chunks=chunks_dict)
    ds_qbot = xr.open_dataset('cesmLE1/atm/proc/tseries/daily/QBOT/b.e11.BRCP85C5CNBDRD.f09_g16.001.cam.h1.QBOT.20810101-21001231.nc', chunks=chunks_dict)
    
    return ds_temp, ds_press, ds_qbot

temp, press, qbot = init_data(chunks_dict={'lat':20,'lon':20})     # Partition 20x20 chunks

# Get time mean of pressure 
press_mean = press1.mean('time')
press_mean['PS'] = press_mean.PS.assign_attrs(units='Pa')

# Calculate vapor pressure and then dewpoint
vapor_pressure = metpy.calc.vapor_pressure(press_mean['PS'], qbot['QBOT'])  
dewpoint = metpy.calc.dewpoint(vapor_pressure)

# Calculate wetbulb
wetbulb = metpy.calc.wet_bulb_temperature(press_mean['PS'], temp['TREFHT'], dewpoint)
```

The dask cluster works fine when calculating dewpoint and for the first set of `metpy.calc.wet_bulb_temperature` processes like opening the datasets, boradcasting, etc, but then it freezes progress at the process shown in the screenshot and returns the following error:

<img width="837" alt="Dask progress" src="https://user-images.githubusercontent.com/65619456/101390381-5ce2b080-3888-11eb-9dea-d9f8f46318bf.png">

```
/home1/ljusten/miniconda3/envs/climate36/lib/python3.6/site-packages/dask/array/core.py:1395: FutureWarning: The `numpy.place` function is not implemented by Dask array. You may want to use the da.map_blocks function or something similar to silence this warning. Your code may stop working in a future release.
  FutureWarning,
/home1/ljusten/miniconda3/envs/climate36/lib/python3.6/site-packages/dask/array/core.py:1395: FutureWarning: The `numpy.place` function is not implemented by Dask array. You may want to use the da.map_blocks function or something similar to silence this warning. Your code may stop working in a future release.
  FutureWarning,
/home1/ljusten/miniconda3/envs/climate36/lib/python3.6/site-packages/dask/array/core.py:1395: FutureWarning: The `numpy.place` function is not implemented by Dask array. You may want to use the da.map_blocks function or something similar to silence this warning. Your code may stop working in a future release.
  FutureWarning,
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /home1/ljusten/miniconda3/envs/climate36/lib/python3.6/site-packages/distributed/comm/core.py:288> exception=CommClosedError()>
Traceback (most recent call last):
  File "/home1/ljusten/miniconda3/envs/climate36/lib/python3.6/site-packages/distributed/comm/core.py", line 297, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/home1/ljusten/miniconda3/envs/climate36/lib/python3.6/asyncio/tasks.py", line 351, in wait_for
    yield from waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/ljusten/miniconda3/envs/climate36/lib/python3.6/site-packages/distributed/comm/core.py", line 304, in _
    raise CommClosedError() from e
distributed.comm.core.CommClosedError
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /home1/ljusten/miniconda3/envs/climate36/lib/python3.6/site-packages/distributed/comm/core.py:288> exception=CommClosedError()>
Traceback (most recent call last):
  File "/home1/ljusten/miniconda3/envs/climate36/lib/python3.6/site-packages/distributed/comm/core.py", line 297, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/home1/ljusten/miniconda3/envs/climate36/lib/python3.6/asyncio/tasks.py", line 351, in wait_for
    yield from waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/ljusten/miniconda3/envs/climate36/lib/python3.6/site-packages/distributed/comm/core.py", line 304, in _
    raise CommClosedError() from e
distributed.comm.core.CommClosedError
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /home1/ljusten/miniconda3/envs/climate36/lib/python3.6/site-packages/distributed/comm/core.py:288> exception=CommClosedError()>
Traceback (most recent call last):
  File "/home1/ljusten/miniconda3/envs/climate36/lib/python3.6/site-packages/distributed/comm/core.py", line 297, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/home1/ljusten/miniconda3/envs/climate36/lib/python3.6/asyncio/tasks.py", line 351, in wait_for
    yield from waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/ljusten/miniconda3/envs/climate36/lib/python3.6/site-packages/distributed/comm/core.py", line 304, in _
    raise CommClosedError() from e
distributed.comm.core.CommClosedError
```
The process actually keeps running after this, but the dask interface shows that none of the workers are being used.

My Conda environment:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
aiohttp                   3.7.3            py36h1d69622_0    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               20.1.0           py36h7b6447c_1  
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10             py36h28b3542_0  
attrs                     20.3.0             pyhd3eb1b0_0  
backcall                  0.2.0                      py_0  
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0  
bokeh                     2.2.3                    py36_0  
brotlipy                  0.7.0           py36h7b6447c_1000  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.10.14                    0  
certifi                   2020.11.8        py36h06a4308_0  
cffi                      1.14.3           py36he30daa8_0  
cftime                    1.2.1            py36heb32a55_0  
chardet                   3.0.4           py36h06a4308_1003  
click                     7.1.2                      py_0  
cloudpickle               1.6.0                      py_0  
contextvars               2.4                        py_0  
cryptography              3.1.1            py36h1ba5d50_0  
curl                      7.71.1               hbc83047_1  
cycler                    0.10.0                   py36_0  
cytoolz                   0.11.0           py36h7b6447c_0  
dask                      2.30.0                     py_0  
dask-core                 2.30.0                     py_0  
dask-labextension         3.0.0                      py_0    conda-forge
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
distributed               2.30.0                   py36_0  
entrypoints               0.3                      py36_0  
expat                     2.2.10               he6710b0_2  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
fsspec                    0.8.3                      py_0  
git                       2.23.0          pl526hacde149_0  
glib                      2.66.1               h92f7085_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.4               hb1b8bf9_0  
heapdict                  1.0.1                      py_0  
icu                       58.2                 he6710b0_3  
idna                      2.10                       py_0  
idna_ssl                  1.1.0           py36h9f0ad1d_1001    conda-forge
immutables                0.14             py36h7b6447c_0  
importlib-metadata        2.0.0                      py_1  
importlib-resources       3.2.1                    pypi_0    pypi
importlib_metadata        2.0.0                         1  
intel-openmp              2020.2                      254  
ipykernel                 5.3.4            py36h5ca1d4c_0  
ipython                   7.16.1           py36h5ca1d4c_0  
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                    py36_0  
ipywidgets                7.5.1                      py_1  
jedi                      0.17.2                   py36_0  
jinja2                    2.11.2                     py_0  
jpeg                      9b                   h024ee3a_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py36_7  
jupyter-server-proxy      1.5.0                      py_0    conda-forge
jupyter_client            6.1.7                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.6.3                    py36_0  
jupyterlab                2.2.9                      py_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         1.2.0                      py_0  
kiwisolver                1.2.0            py36hfd86e86_0  
krb5                      1.18.2               h173b8e3_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libcurl                   7.71.1               h20c2e04_1  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libnetcdf                 4.7.3                hb80b6cc_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
locket                    0.2.0                    py36_1  
lz4-c                     1.9.2                heb0550a_3  
markupsafe                1.1.1            py36h7b6447c_0  
matplotlib                3.3.2                         0  
matplotlib-base           3.3.2            py36h817c723_0  
metpy                     1.0.0rc2.post81+ge63b136c          pypi_0    pypi
mistune                   0.8.4            py36h7b6447c_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.2.0            py36h23d657b_0  
mkl_random                1.1.1            py36h0573a6f_0  
msgpack-python            1.0.0            py36hfd86e86_1  
multidict                 4.7.5            py36h8c4c3a4_2    conda-forge
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py36_0  
nbformat                  5.0.8                      py_0  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.4.2              pyhd3eb1b0_0  
netcdf4                   1.5.3            py36hbf33ddf_0  
nodejs                    10.13.0              he6710b0_0  
notebook                  6.1.4                    py36_0  
numpy                     1.19.2           py36h54aff64_0  
numpy-base                1.19.2           py36hfa32c7d_0  
olefile                   0.46                     py36_0  
openssl                   1.1.1h               h7b6447c_0  
packaging                 20.4                       py_0  
pandas                    1.1.3            py36he6710b0_0  
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.3            py36h06a4308_1  
parso                     0.7.0                      py_0  
partd                     1.1.0                      py_0  
pcre                      8.44                 he6710b0_0  
perl                      5.26.2               h14c3975_0  
pexpect                   4.8.0                    py36_0  
pickleshare               0.7.5                    py36_0  
pillow                    8.0.1            py36he98fc37_0  
pint                      0.16.1                   pypi_0    pypi
pip                       20.2.4           py36h06a4308_0  
pooch                     1.2.0                    pypi_0    pypi
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
psutil                    5.7.2            py36h7b6447c_0  
ptyprocess                0.6.0                    py36_0  
pycparser                 2.20                       py_2  
pygments                  2.7.2              pyhd3eb1b0_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyproj                    2.6.1.post1              pypi_0    pypi
pyqt                      5.9.2            py36h05f1152_2  
pyrsistent                0.17.3           py36h7b6447c_0  
pysocks                   1.7.1            py36h06a4308_0  
python                    3.6.12               hcff3b4d_2  
python-dateutil           2.8.1                      py_0  
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.1                     py_0  
pyyaml                    5.3.1            py36h7b6447c_1  
pyzmq                     19.0.2           py36he6710b0_1  
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h7b6447c_0  
requests                  2.24.0                     py_0  
scipy                     1.5.2            py36h0b6359f_0  
seaborn                   0.11.0                     py_0  
send2trash                1.5.0                    py36_0  
setuptools                50.3.0           py36hb0f4dca_1  
simpervisor               0.3                        py_1    conda-forge
sip                       4.19.8           py36hf484d3e_0  
six                       1.15.0                     py_0  
sortedcontainers          2.2.2                      py_0  
sqlite                    3.33.0               h62c20be_0  
tblib                     1.7.0                      py_0  
terminado                 0.9.1                    py36_0  
testpath                  0.4.4                      py_0  
tk                        8.6.10               hbc83047_0  
toolz                     0.11.1                     py_0  
tornado                   6.0.4            py36h7b6447c_1  
traitlets                 4.3.3                    py36_0  
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0  
urllib3                   1.25.11                    py_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py36_1  
wheel                     0.35.1                     py_0  
widgetsnbextension        3.5.1                    py36_0  
xarray                    0.16.1                     py_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yarl                      1.6.3            py36h1d69622_0    conda-forge
zeromq                    4.3.3                he6710b0_3  
zict                      2.0.0                      py_0  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0
```

**Comment by rabernat** [comment]
Hi @lennijusten - welcome to xgcm!

Did you mean to open this issue in the xgcm repo? At first glance it appears to have nothing to do with xgcm. Am I missing something?

**Comment by lennijusten** [comment]
Hi Ryan,

I appear to have lost my way haha. No you are right: this is meant for Metpy. Sorry about that! Moving it now.

Best,
Lenni

**Comment by lennijusten** [comment]
Moved to Metpy
