### ISSUE TITLE
error raised when diff a reduced variable

### ISSUE THREAD

**Issue by miniufo** [xgcm/xgcm#309]
I add proper metrics to the `grid` object.  A 4D DataArray, say `T(time, Z, YC, XC)`, can be `diff`ed along any dimension.  However, when I take a zonal mean `Tm = T.mean('XC')`, `Tm(time, Z, YC)` cannot be `diff`ed along 'Y'.  "Unable to find any combinations of metrics" error is raised again.

I guess this is because the reduced variable `Tm` does not have the same dimensions as the metrics (the 'X' dim is removed during zonal mean).  But as a user, I expect this is a normal operation.  Is there any way to deal with this case?

**Comment by jbusecke** [comment]
Hi @miniufo, I am not sure I completely understand the problem. Could you share some more details about e.g. the metrics, the dataset etc? `grid.diff()` should never invoke a metric, only `grid.derivative()`.

**Comment by miniufo** [comment]
Yes, I used `grid.derivative`.  I want to calculate the zonal-mean stratification.

**Comment by jbusecke** [comment]
I think you will need to setup a new grid object for the averaged dataset. Check with the averaged version if it has the appropriate `dy` metrics (I am not sure what happens to 2d coordinates upon averaging. You might have to construct that seperately!

**Comment by rabernat** [comment]
> I think you will need to setup a new grid object for the averaged dataset.

Ideally we could avoid this _if the metric is a scalar_.

@miniufo could you share a lot more info about your data? Please share the output of `print(T)`, `print(Tm)`, and `print(grid)`, plus the full code you are calling (e.g. `grid.derivative(...)`). That will help us understand your situation better.

**Comment by jbusecke** [comment]
I was actually wondering if we allow scalar metrics. That would be relevant for #306 too.

**Comment by miniufo** [comment]
`print(T)` gives:
```python
<xarray.DataArray 'THETA' (time: 60, Z: 30, YC: 400, XC: 200)>
dask.array<concatenate, shape=(60, 30, 400, 200), dtype=float32, chunksize=(1, 30, 400, 200), chunktype=numpy.ndarray>
Coordinates:
  * XC       (XC) float32 2.5 7.5 12.5 17.5 22.5 ... 982.5 987.5 992.5 997.5
  * YC       (YC) float32 2.5 7.5 12.5 17.5 ... 1.988e+03 1.992e+03 1.998e+03
  * Z        (Z) >f4 -5.0 -15.0 -27.5 -45.0 ... -2.58e+03 -2.83e+03 -3.08e+03
    rA       (YC, XC) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    Depth    (YC, XC) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    drF      (Z) >f4 10.0 10.0 15.0 20.0 20.0 ... 200.0 250.0 250.0 250.0 250.0
    PHrefC   (Z) >f4 49.05 147.1 269.8 441.5 ... 2.531e+04 2.776e+04 3.021e+04
    hFacC    (Z, YC, XC) >f4 dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    maskC    (Z, YC, XC) bool dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    maskInC  (YC, XC) bool dask.array<chunksize=(400, 200), meta=np.ndarray>
    rhoRef   (Z) >f4 999.8 999.8 999.8 999.8 999.8 ... 999.8 999.8 999.8 999.8
    iter     (time) int32 6221088 6221376 6221664 ... 6237504 6237792 6238080
  * time     (time) timedelta64[ns] 21601 days 21602 days ... 21660 days
    dxF      (YC, XC) float32 dask.array<chunksize=(400, 199), meta=np.ndarray>
    dyF      (YC, XC) float32 dask.array<chunksize=(399, 200), meta=np.ndarray>
    yA       (Z, YC, XC) float32 dask.array<chunksize=(30, 400, 199), meta=np.ndarray>
Attributes:
    standard_name:  THETA
    long_name:      Potential Temperature
    units:          degC
```

`print(Tm)` gives:
```python
<xarray.DataArray 'THETA' (time: 60, Z: 30, YC: 400)>
array([[[0.        , 1.651849  , 1.6926101 , ..., 5.143432  ,
         5.238152  , 7.916161  ],
        [0.        , 1.6516976 , 1.6917577 , ..., 5.130691  ,
         5.21262   , 7.833158  ],
        [0.        , 1.6500741 , 1.6875968 , ..., 5.0526824 ,
         5.0964    , 7.7509785 ],
        ...,
        [0.        , 0.88205034, 0.882365  , ..., 1.3343159 ,
         1.3282493 , 0.29043302],
        [0.        , 0.8260485 , 0.8325609 , ..., 0.909568  ,
         0.9043634 , 0.13199452],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00860249]]], dtype=float32)
Coordinates:
  * YC       (YC) float32 2.5 7.5 12.5 17.5 ... 1.988e+03 1.992e+03 1.998e+03
  * Z        (Z) >f4 -5.0 -15.0 -27.5 -45.0 ... -2.58e+03 -2.83e+03 -3.08e+03
    drF      (Z) >f4 10.0 10.0 15.0 20.0 20.0 ... 200.0 250.0 250.0 250.0 250.0
    PHrefC   (Z) >f4 49.05 147.1 269.8 441.5 ... 2.531e+04 2.776e+04 3.021e+04
    rhoRef   (Z) >f4 999.8 999.8 999.8 999.8 999.8 ... 999.8 999.8 999.8 999.8
    iter     (time) int32 6221088 6221376 6221664 ... 6237504 6237792 6238080
  * time     (time) timedelta64[ns] 21601 days 21602 days ... 21660 days
```

`print(grid)` gives:
```python
<xgcm.Grid>
Y Axis (not periodic, boundary=None):
  * center   YC --> left
  * left     YG --> center
T Axis (not periodic, boundary=None):
  * center   time
Z Axis (not periodic, boundary=None):
  * center   Z --> left
  * left     Zl --> center
  * outer    Zp1 --> center
  * right    Zu --> center
X Axis (periodic, boundary=None):
  * center   XC --> left
  * left     XG --> center
```

`grid.derivative(T, 'Y', boundary='extend')` gives:
```python
<xarray.DataArray (time: 60, Z: 30, YG: 400, XC: 200)>
dask.array<truediv, shape=(60, 30, 400, 200), dtype=float32, chunksize=(1, 30, 399, 200), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) timedelta64[ns] 21601 days 21602 days ... 21660 days
  * Z        (Z) >f4 -5.0 -15.0 -27.5 -45.0 ... -2.58e+03 -2.83e+03 -3.08e+03
  * YG       (YG) >f4 0.0 5e+03 1e+04 1.5e+04 ... 1.985e+06 1.99e+06 1.995e+06
  * XC       (XC) >f4 2.5e+03 7.5e+03 1.25e+04 ... 9.875e+05 9.925e+05 9.975e+05
```

`grid.derivative(Tm, 'Y', boundary='extend')` gives:
```python
Traceback (most recent call last):

  File "<ipython-input-3-67d1607cde7e>", line 1, in <module>
    grid.derivative(Tm, 'Y', boundary='extend')

  File "C:\ProgramData\Anaconda3\lib\site-packages\xgcm\grid.py", line 1662, in derivative
    dx = self.get_metric(diff, (axis,))

  File "C:\ProgramData\Anaconda3\lib\site-packages\xgcm\grid.py", line 1341, in get_metric
    raise KeyError(

KeyError: "Unable to find any combinations of metrics for array dims {'time', 'YG', 'Z'} and axes ('Y',)"
```

**Comment by rabernat** [comment]
Fantastic. Just need one more piece of information...how are you creating your `grid` object? What are the metrics you are using?

**Comment by miniufo** [comment]
I write a simple function to add missing metrics for my default use case:
```python
def add_MITgcm_missing_metrics(dset, periodic=None):
    """
    Infer missing metrics from MITgcm output files.

    Parameters
    ----------
    dset : xarray.Dataset
        A dataset open from a file

    Return
    -------
    dset : xarray.Dataset
        Input dataset with appropriated metrics added
    grid : xgcm.Grid
        The grid with appropriated metrics
    """
    coords = dset.coords
    grid   = Grid(dset, periodic=periodic)
    
    BCx = 'periodic' if grid.axes['X']._periodic else 'fill'
    BCy = 'periodic' if grid.axes['Y']._periodic else 'fill'
    
    if 'drW' not in coords: # vertical cell size at u point
        coords['drW'] = dset.hFacW * dset.drF
    if 'drS' not in coords: # vertical cell size at v point
        coords['drS'] = dset.hFacS * dset.drF
    if 'drC' not in coords: # vertical cell size at tracer point
        coords['drC'] = dset.hFacC * dset.drF
    if 'drG' not in coords: # vertical cell size at tracer point
        coords['drG'] = xr.DataArray(dset.drC[:-1].values, dims='Zl',
                                     coords={'Zl':dset.Zl.values})
    
    if 'dxF' not in coords:
        coords['dxF'] = grid.interp(dset.dxC, 'X', boundary=BCx)
    if 'dyF' not in coords:
        coords['dyF'] = grid.interp(dset.dyC, 'Y', boundary=BCy)
    if 'dxV' not in coords:
        coords['dxV'] = grid.interp(dset.dxG, 'X', boundary=BCx)
    if 'dyU' not in coords:
        coords['dyU'] = grid.interp(dset.dyG, 'Y', boundary=BCy)
    
    if 'hFacZ' not in coords:
        coords['hFacZ'] = grid.interp(dset.hFacS, 'X', boundary=BCx)
    if 'maskZ' not in coords:
        coords['maskZ'] = coords['hFacZ']
        
    if 'yA' not in coords:
        coords['yA'] = dset.drF * dset.hFacC * dset.dxF
    
    # Calculate vertical distances located on the cellboundary
    # ds.coords['dzC'] = grid.diff(ds.depth, 'Z', boundary='extrapolate')
    # Calculate vertical distances located on the cellcenter
    # ds.coords['dzT'] = grid.diff(ds.depth_left, 'Z', boundary='extrapolate')
    
    metrics = {
        ('X',)    : ['dxG', 'dxF', 'dxC', 'dxV'], # X distances
        ('Y',)    : ['dyG', 'dyF', 'dyC', 'dyU'], # Y distances
        ('Z',)    : ['drW', 'drS', 'drC', 'drF', 'drG'], # Z distances
        ('X', 'Y'): ['rAw', 'rAs', 'rA' , 'rAz'], # Areas in X-Y plane
        ('X', 'Z'): ['yA']} # Areas in X-Z plane
    
    grid._assign_metrics(metrics)
    
    return dset, grid
```
and just simply call `dset, grid = add_MITgcm_missing_metrics(dset, periodic=['X'])`

**Comment by rabernat** [comment]
Wow, this is great! So useful to see this function.

The fundamental problem is that your Y-axis metrics (`'dyG', 'dyF', 'dyC', 'dyU'`) are 2D variables. So when you call `grid.derivative(Tm, 'Y')`, there is no way to align the metric with `Tm`.

You have two options:
- Is there actually any variation in `dyG` in the X direction? If not, you can simply reduce the dimensionality of your metrics _before_ creating the Grid, i.e. `dyG = dyG[:, 0]. Then it should work. This option is not good, however, if you have a curvilinear grid whose metrics vary spatially in 2D. But in that case, what does the Y-derivative of the X average even mean?
- Take the Y derivative _first_, i.e. `grid.derivative(T, 'Y', boundary='extend').mean(dim='XG')`.

**Comment by miniufo** [comment]
Thanks @rabernat, I am now using the second option.  But I am not expecting this error.  Could `xgcm` automatically 'overlook' the dimension of the metrics that is absent from the given (reduced) variable?

**Comment by rabernat** [comment]
> Could `xgcm` automatically 'overlook' the dimension of the metrics that is absent from the given (reduced) variable?

I don't see how this could be possible in general. You need a Y metric to take a derivative in the Y direction. If your Y metric is variable in the X direction, there is simply no accurate way to ignore this.

**Comment by miniufo** [comment]
OK, I understand the concern now.  Metric Y could generally vary with X.  So take derivative first before the zonal mean is a good solution if the variable is loaded as `dask`.  Thanks@ @rabernat @jbusecke .  Close this now.
