### ISSUE TITLE
How to construct vertical metrics after interpolating onto a tracer coordinate?

### ISSUE THREAD

**Issue by miniufo** [xgcm/xgcm#312]
I **though** I understand the metrics but it looks not.  I interpolated a dataset onto a tracer `THETA` coordinate, and added proper vertical coordinates at cell face and outer points.  But when I perform `grid.cumint(-v. 'THETA', boundary='extend')` using interpolated `v`, `Unable to find any combinations of metrics` error was raised again...

I've read the [transform manual](https://xgcm.readthedocs.io/en/latest/transform.html) very carefully but I do not find the solution.  Below is the `dset`:
```python
<xarray.Dataset>
Dimensions:  (THETA: 51, THETA_c: 52, THETA_l: 51, THETA_u: 51, XC: 200, YC: 400, time: 60)
Coordinates:
  * XC       (XC) float32 2.5e+03 7.5e+03 1.25e+04 ... 9.925e+05 9.975e+05
  * YC       (YC) float32 2.5e+03 7.5e+03 1.25e+04 ... 1.992e+06 1.998e+06
    rA       (YC, XC) float32 dask.array<chunksize=(400, 200), meta=np.ndarray>
    Depth    (YC, XC) float32 dask.array<chunksize=(400, 200), meta=np.ndarray>
    maskInC  (YC, XC) bool dask.array<chunksize=(400, 200), meta=np.ndarray>
    iter     (time) int32 dask.array<chunksize=(5,), meta=np.ndarray>
  * time     (time) timedelta64[ns] 21601 days 21602 days ... 21660 days
    dxF      (YC, XC) float32 dask.array<chunksize=(400, 200), meta=np.ndarray>
    dyF      (YC, XC) float32 dask.array<chunksize=(400, 200), meta=np.ndarray>
  * THETA    (THETA) float64 0.0 0.1 0.2 0.3 0.4 0.5 ... 4.5 4.6 4.7 4.8 4.9 5.0
  * THETA_l  (THETA_l) float64 -0.05 0.05 0.15 0.25 0.35 ... 4.65 4.75 4.85 4.95
  * THETA_u  (THETA_u) float64 0.05 0.15 0.25 0.35 0.45 ... 4.75 4.85 4.95 5.05
  * THETA_c  (THETA_c) float64 -0.05 0.05 0.15 0.25 0.35 ... 4.75 4.85 4.95 5.05
    drC      (THETA_c) float64 0.1 0.1 0.1 0.1 0.1 0.1 ... 0.1 0.1 0.1 0.1 0.1
    drG      (THETA_l) float64 0.1 0.1 0.1 0.1 0.1 0.1 ... 0.1 0.1 0.1 0.1 0.1
    drF      (THETA) float64 0.1 0.1 0.1 0.1 0.1 0.1 ... 0.1 0.1 0.1 0.1 0.1 0.1
Data variables:
    T        (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>
    U        (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>
    V        (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>
    Z        (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>
```
and `grid`:
```python
<xgcm.Grid>
THETA Axis (not periodic, boundary=None):
  * center   THETA --> left
  * left     THETA_l --> center
  * right    THETA_u --> center
  * outer    THETA_c --> center
X Axis (periodic, boundary=None):
  * center   XC
Y Axis (not periodic, boundary=None):
  * center   YC
```

Can you guys help me find out why the error is raised again?  Why the [examples in the transform manual](https://xgcm.readthedocs.io/en/latest/transform.html) do not construct any `metrics` but only assign `coords` to the `grid` object?

**Comment by jbusecke** [comment]
You might have to create your own metric. In this case I think you need to conservatively transform `drF` onto THETA (you might have to broadcast it against `XC` and `YC` first. 

Let me know if this works. BTW, I am working on improving `grid.transform()`, so this is done automatically. I have a working version, but not enough time at the moment. But in the future this might be added.

**Comment by miniufo** [comment]
>BTW, I am working on improving grid.transform(), so this is done automatically.

Glad to know this will be automatically done in the future.

>  In this case I think you need to conservatively transform drF onto THETA

There is a little confusing.  I define the THETA-sapce my self, using `np.linspace` to generate a uniform set of contours between min and max.  I could also define the cell boundaries.  Why do I need to transform `drF` rather than define it manually?  I definitely need `conservative` option, but I think `linear` option is not too bad for my current case.

**Comment by jbusecke** [comment]
> I define the THETA-sapce my self, using np.linspace to generate a uniform set of contours between min and max. I could also define the cell boundaries. 

You will definitely have to do that, yes. 

If your depth is not changing in time, interpolating the depth onto theta_bounds will produce the exact same results. But if you are using a z* or other vertical grid, where the cell thicknesses actually vary in time and/or space, it is more precise to use the actual cell thickness (which you can think of as an extensive variable!). Since your `drF` is indeed static I think it does not matter!

**Comment by miniufo** [comment]
Thanks @jbusecke.  My case is static z (not z*).  So I construct `THETA` as the vertical cell center, `THETA_l` and `THETA_u` as lower and upper cell boundaries, and `THETA_c` as outer metrics, as output in the first post.  But  the error is raised even when I called `grid.get_metric(v, 'THETA')`.  I tried broadcasting the `drF`, `drC`, and `drG` metrics to `XC` and `YC`:
```python
<xarray.Dataset>
Dimensions:  (THETA: 51, THETA_c: 52, THETA_l: 51, THETA_u: 51, XC: 200, YC: 400, time: 60)
Coordinates:
  * XC       (XC) float32 2.5e+03 7.5e+03 1.25e+04 ... 9.925e+05 9.975e+05
  * YC       (YC) float32 2.5e+03 7.5e+03 1.25e+04 ... 1.992e+06 1.998e+06
    rA       (YC, XC) float32 dask.array<chunksize=(400, 200), meta=np.ndarray>
    Depth    (YC, XC) float32 dask.array<chunksize=(400, 200), meta=np.ndarray>
    maskInC  (YC, XC) bool dask.array<chunksize=(400, 200), meta=np.ndarray>
    iter     (time) int32 dask.array<chunksize=(5,), meta=np.ndarray>
  * time     (time) timedelta64[ns] 21601 days 21602 days ... 21660 days
    dxF      (YC, XC) float32 dask.array<chunksize=(400, 200), meta=np.ndarray>
    dyF      (YC, XC) float32 dask.array<chunksize=(400, 200), meta=np.ndarray>
  * THETA    (THETA) float64 0.0 0.1 0.2 0.3 0.4 0.5 ... 4.5 4.6 4.7 4.8 4.9 5.0
  * THETA_l  (THETA_l) float64 -0.05 0.05 0.15 0.25 0.35 ... 4.65 4.75 4.85 4.95
  * THETA_u  (THETA_u) float64 0.05 0.15 0.25 0.35 0.45 ... 4.75 4.85 4.95 5.05
  * THETA_c  (THETA_c) float64 -0.05 0.05 0.15 0.25 0.35 ... 4.75 4.85 4.95 5.05
    drC      (THETA_c, YC, XC) float64 0.1 0.1 0.1 0.1 0.1 ... 0.1 0.1 0.1 0.1
    drG      (THETA_l, YC, XC) float64 0.1 0.1 0.1 0.1 0.1 ... 0.1 0.1 0.1 0.1
    drF      (THETA, YC, XC) float64 0.1 0.1 0.1 0.1 0.1 ... 0.1 0.1 0.1 0.1 0.1
Data variables:
    T        (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>
    U        (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>
    V        (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>
    Z        (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>

```
 and this does not help...

**Comment by rabernat** [comment]
> I tried broadcasting the `drF`, `drC`, and `drG` metrics to `XC` and `YC`:

If you are transforming to THETA coordinates, in order to get the THETA-layer thickness, I think you need to explictly call `transform` on `drF`, ideally using the conservative scheme. It doesn't make sense to me that we are returning a dataset with coordinates like

```
drF      (THETA) float64
```

In THETA space, `drF` is inherently 4D. So broadcasting won't solve this problem.

**Comment by jbusecke** [comment]
To clarify my previous comment: I meant that you might have to broadcast `drF` *before* transforming it (you basically want an array that has `drF` on each grid position but is the same shape as e.g. `T`, and then transform that onto the theta bounds with `method='conservative'`). 

I agree with @rabernat that returning a 1D `drF` is not right. Could you post the full code you use to do that?

**Comment by miniufo** [comment]
Thanks for you guys @rabernat @jbusecke.  This is a worked code snippet:
```python
T = dset.THETA
U = grid.interp(dset.UVEL, 'X').rename('U')
V = grid.interp(dset.VVEL, 'Y', boundary='fill').rename('V')
Z = (T-T+dset.Z).rename('Z') # broadcast
drF = (T-T+dset.drF).rename('drF') # broadcast

# define the target values in density
T_target = np.linspace(0, 5, 51)

# and transform
T_interp = grid.transform(T.where(T!=0), 'Z', T_target, method='linear',
                          target_data=T).transpose('time','THETA','YC','XC')
U_interp = grid.transform(U.where(T!=0), 'Z', T_target, method='linear',
                          target_data=T).transpose('time','THETA','YC','XC')
V_interp = grid.transform(V.where(T!=0), 'Z', T_target, method='linear',
                          target_data=T).transpose('time','THETA','YC','XC')
Z_interp = grid.transform(Z.where(T!=0), 'Z', T_target, method='linear',
                          target_data=T).transpose('time','THETA','YC','XC')
drF_interp = grid.transform(drF, 'Z', T_target, method='linear',
                            target_data=T).transpose('time','THETA','YC','XC')

xr.merge([T_interp.rename('T'), U_interp, V_interp,
          Z_interp]).to_netcdf(indir + 'density.nc')
```

Original `dset` is:
```python
<xarray.Dataset>
Dimensions:  (XC: 200, XG: 200, YC: 400, YG: 400, Z: 30, Zl: 30, Zp1: 31, Zu: 30, time: 60)
Coordinates:
  * XC       (XC) >f4 2.5e+03 7.5e+03 1.25e+04 ... 9.875e+05 9.925e+05 9.975e+05
  * YC       (YC) >f4 2.5e+03 7.5e+03 1.25e+04 ... 1.988e+06 1.992e+06 1.998e+06
  * XG       (XG) >f4 0.0 5e+03 1e+04 1.5e+04 ... 9.85e+05 9.9e+05 9.95e+05
  * YG       (YG) >f4 0.0 5e+03 1e+04 1.5e+04 ... 1.985e+06 1.99e+06 1.995e+06
  * Z        (Z) >f4 -5.0 -15.0 -27.5 -45.0 ... -2.58e+03 -2.83e+03 -3.08e+03
  * Zp1      (Zp1) >f4 0.0 -10.0 -20.0 ... -2.705e+03 -2.955e+03 -3.205e+03
  * Zu       (Zu) >f4 -10.0 -20.0 -35.0 ... -2.705e+03 -2.955e+03 -3.205e+03
  * Zl       (Zl) >f4 0.0 -10.0 -20.0 -35.0 ... -2.455e+03 -2.705e+03 -2.955e+03
    rA       (YC, XC) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    dxG      (YG, XC) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    dyG      (YC, XG) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    Depth    (YC, XC) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    rAz      (YG, XG) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    dxC      (YC, XG) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    dyC      (YG, XC) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    rAw      (YC, XG) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    rAs      (YG, XC) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    drC      (Zp1) >f4 dask.array<chunksize=(31,), meta=np.ndarray>
    drF      (Z) >f4 dask.array<chunksize=(30,), meta=np.ndarray>
    PHrefC   (Z) >f4 dask.array<chunksize=(30,), meta=np.ndarray>
    PHrefF   (Zp1) >f4 dask.array<chunksize=(31,), meta=np.ndarray>
    hFacC    (Z, YC, XC) >f4 dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    hFacW    (Z, YC, XG) >f4 dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    hFacS    (Z, YG, XC) >f4 dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    maskC    (Z, YC, XC) bool dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    maskW    (Z, YC, XG) bool dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    maskS    (Z, YG, XC) bool dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    maskInC  (YC, XC) bool dask.array<chunksize=(400, 200), meta=np.ndarray>
    maskInS  (YG, XC) bool dask.array<chunksize=(400, 200), meta=np.ndarray>
    maskInW  (YC, XG) bool dask.array<chunksize=(400, 200), meta=np.ndarray>
    rhoRef   (Z) >f4 dask.array<chunksize=(30,), meta=np.ndarray>
    iter     (time) int32 dask.array<chunksize=(1,), meta=np.ndarray>
  * time     (time) timedelta64[ns] 21601 days 21602 days ... 21660 days
    drW      (Z, YC, XG) float32 dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    drS      (Z, YG, XC) float32 dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    drG      (Zl) >f4 5.0 10.0 12.5 17.5 20.0 ... 200.0 225.0 250.0 250.0 250.0
    dxF      (YC, XC) float32 dask.array<chunksize=(400, 199), meta=np.ndarray>
    dyF      (YC, XC) float32 dask.array<chunksize=(399, 200), meta=np.ndarray>
    dxV      (YG, XG) float32 dask.array<chunksize=(400, 1), meta=np.ndarray>
    dyU      (YG, XG) float32 dask.array<chunksize=(1, 200), meta=np.ndarray>
    hFacZ    (Z, YG, XG) float32 dask.array<chunksize=(30, 400, 1), meta=np.ndarray>
    maskZ    (Z, YG, XG) float32 dask.array<chunksize=(30, 400, 1), meta=np.ndarray>
    yA       (Z, YC, XC) float32 dask.array<chunksize=(30, 400, 199), meta=np.ndarray>
Data variables:
    UVEL     (time, Z, YC, XG) float32 dask.array<chunksize=(1, 30, 400, 200), meta=np.ndarray>
    VVEL     (time, Z, YG, XC) float32 dask.array<chunksize=(1, 30, 400, 200), meta=np.ndarray>
    WVEL     (time, Zl, YC, XC) float32 dask.array<chunksize=(1, 30, 400, 200), meta=np.ndarray>
    THETA    (time, Z, YC, XC) float32 dask.array<chunksize=(1, 30, 400, 200), meta=np.ndarray>
```

Several questions here:
1. If 'conservative' option is used, error is raised:
```python
Traceback (most recent call last):

  File "E:\OneDrive\Python\MyPack\Projects\Channel\VInterp.py", line 36, in <module>
    T_interp = grid.transform(T.where(T!=0), 'Z', T_target, method='conservative',

  File "C:\ProgramData\Anaconda3\lib\site-packages\xgcm\grid.py", line 1819, in transform
    return ax.transform(da, target, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\xgcm\grid.py", line 960, in transform
    out = conservative_interpolation(

  File "C:\ProgramData\Anaconda3\lib\site-packages\xgcm\transform.py", line 189, in wrapper_input_handling
    value = func(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\xgcm\transform.py", line 227, in conservative_interpolation
    out = xr.apply_ufunc(

  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\core\computation.py", line 1128, in apply_ufunc
    return apply_dataarray_vfunc(

  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\core\computation.py", line 271, in apply_dataarray_vfunc
    result_var = func(*data_vars)

  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\core\computation.py", line 628, in apply_variable_ufunc
    input_data = [

  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\core\computation.py", line 629, in <listcomp>
    broadcast_compat_data(arg, broadcast_dims, core_dims)

  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\core\computation.py", line 554, in broadcast_compat_data
    raise ValueError(

ValueError: operand to apply_ufunc has required core dimensions ['Zp1'], but some of these dimensions are absent on an input variable: ['Zp1']
```
2. How to transform `U` and `V` that are not defined on tracer point?  Here I have to interpolate them onto tracer point first.
3. Do I need to mask the variables using like `T.where(T!=0)` in the call of `transform`?
4. Is `drF` correctly transformed here?

**Comment by jbusecke** [comment]
1. I dont understand where this dimension even comes from? What does your grid look like in the vertical?
2. You have to horizontally interpolate. Either U/V onto the tracer point or your target data (`T`) onto the velocity positions. Depends on your goals afterwards!
3. That also depends on why you are doing that. I don't see the point of doing that with U and V here (they are already masked), but you have to do some masking with the broadcasted depth and thickness, I believe.
4. Not sure. I would always check an example (e.g. a single profile) to make sure about this.

**Comment by miniufo** [comment]
Here is my original vertical grid (a simple MITgcm simultion): `dset.Z.plot()`
![image](https://user-images.githubusercontent.com/9312831/108527882-c44bc080-730d-11eb-9ccf-d640e18cdac3.png)
also see `dset.drF.plot()`
![image](https://user-images.githubusercontent.com/9312831/108527933-d594cd00-730d-11eb-8925-3c61b151a87f.png)
I also checked the drF after interpolation for some random points: `drF_interp[...].plot()`
![image](https://user-images.githubusercontent.com/9312831/108528190-1b519580-730e-11eb-9359-229404f374e8.png)
![image](https://user-images.githubusercontent.com/9312831/108528210-2278a380-730e-11eb-9dfb-080d56009f0c.png)

But this is the result for `linear` case, and it is still raising the `Unable to find any combinations of metrics` error using the `drF_interp`.

The (linear) interpolated `dset` is now:
```python
<xarray.Dataset>
Dimensions:  (THETA: 51, XC: 200, YC: 400, time: 60)
Coordinates:
  * XC       (XC) float32 2.5e+03 7.5e+03 1.25e+04 ... 9.925e+05 9.975e+05
  * YC       (YC) float32 2.5e+03 7.5e+03 1.25e+04 ... 1.992e+06 1.998e+06
    rA       (YC, XC) float32 dask.array<chunksize=(400, 200), meta=np.ndarray>
    Depth    (YC, XC) float32 dask.array<chunksize=(400, 200), meta=np.ndarray>
    maskInC  (YC, XC) bool dask.array<chunksize=(400, 200), meta=np.ndarray>
    iter     (time) int32 6221088 6221376 6221664 ... 6237504 6237792 6238080
  * time     (time) timedelta64[ns] 21601 days 21602 days ... 21660 days
    dxF      (YC, XC) float32 dask.array<chunksize=(400, 200), meta=np.ndarray>
    dyF      (YC, XC) float32 dask.array<chunksize=(400, 200), meta=np.ndarray>
  * THETA    (THETA) float64 0.0 0.1 0.2 0.3 0.4 0.5 ... 4.5 4.6 4.7 4.8 4.9 5.0
Data variables:
    T        (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>
    U        (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>
    V        (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>
    Z        (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>
    drF      (time, THETA, YC, XC) float64 dask.array<chunksize=(5, 6, 400, 200), meta=np.ndarray>
```
Do you have any clue on this? @jbusecke

**Comment by jbusecke** [comment]
I have to admit I am a bit lost here. Could you maybe come up with a self contained example (make up a small dataset with similar properties as your own), which I could run on my end? If you can reproduce the error with that it would help tremendously with pinning down what is going on here.

**Comment by miniufo** [comment]
I made a sample dataset [from here](https://github.com/miniufo/channel/blob/master/dsetZ.nc) and you may play with it and the following code snippet:
```python
import numpy as np
import xarray as xr
from xgcm import Grid


def add_MITgcm_missing_metrics(dset, periodic=None):
    """
    Infer missing metrics from MITgcm output files.

    Parameters
    ----------
    dset : xarray.Dataset
        A dataset open from a file

    Return
    -------
    dset : xarray.Dataset
        Input dataset with appropriated metrics added
    grid : xgcm.Grid
        The grid with appropriated metrics
    """
    grid   = Grid(dset, periodic=periodic)
    
    metrics = {
        ('X',)    : ['dxG', 'dxC'], # X distances
        ('Y',)    : ['dyG', 'dyC'], # Y distances
        ('Z',)    : ['drC', 'drF'], # Z distances
        ('X', 'Y'): ['rAw', 'rAs', 'rA' , 'rAz'], # Areas in X-Y plane
    } # Areas in X-Z plane
    
    grid._assign_metrics(metrics)
    
    return dset, grid


# load data
dsetZ = xr.open_dataset('D:/dsetZ.nc')

# add metrics
dsetZ, gridZ = add_MITgcm_missing_metrics(dsetZ, periodic=['X'])

# interpolate onto T
T = dsetZ.THETA
V = gridZ.interp(dsetZ.VVEL, 'Y', boundary='extend').rename('V')
Z = (T-T+dsetZ.Z).rename('Z') # broadcast
drF = (T-T+dsetZ.drF).rename('drF') # broadcast
sfZ = gridZ.cumint(V, 'Z', boundary='extend') # overturning in Z

# define T coord
T_target = np.linspace(0.7, 5.7, 26)

# and transform
T_interp = gridZ.transform(T, 'Z', T_target, method='linear',
                          target_data=T).transpose('THETA','YC','XC')
V_interp = gridZ.transform(V, 'Z', T_target, method='linear',
                          target_data=T).transpose('THETA','YC','XC')
Z_interp = gridZ.transform(Z, 'Z', T_target, method='linear',
                          target_data=T).transpose('THETA','YC','XC')
drF_interp = gridZ.transform(drF, 'Z', T_target, method='linear',
                            target_data=T).transpose('THETA','YC','XC')

# write data
xr.merge([T_interp.rename('T'), V_interp, Z_interp,
          drF_interp]).to_netcdf('d:/dsetT.nc')
```

Then you have the transformed dataset `dsetT.nc`.  However, when I change `method` from `linear` to `conservative`, error about `Zp1` will be raised.  Only `linear` is OK now.

I also tried calculating the overturning streamfunction in T-space as:
```python
import numpy as np

# read in data in T-coord
dsetT = xr.open_dataset('d:/dsetT.nc')

# define cell boundaries
inc = np.append(dsetT.THETA.diff('THETA').values, [0.05])

dsetT['THETA_l'] = xr.DataArray((dsetT.THETA-inc).values, dims='THETA_l')
dsetT['THETA_u'] = xr.DataArray((dsetT.THETA+inc).values, dims='THETA_u')

metrics = {
    # ('X',)    : ['dxF',], # X distances
    # ('Y',)    : ['dyF',], # Y distances
    ('Z',)    : ['drF',], # Z distances
    # ('THETA',)    : ['drG', 'drF', 'drC',], # Z distances
    } # Areas in X-Z plane

gridT = Grid(dsetT, periodic=['X'],
            coords={'Z': {'center': 'THETA',
                          'left'  : 'THETA_l',
                          'right' : 'THETA_u',
                          # 'outer' : 'THETA_c'
                              },
                    'X': {'center': 'XC'},
                    'Y': {'center': 'YC'}},
            metrics=metrics)

# zonal-mean states
v = dsetT.V
z = dsetT.Z
T = dsetT.T
h = z.differentiate('THETA')

# cal overturning in theta-space
sfT = gridT.cumint(v*h, 'Z', boundary='extend')
```

During my simplification of the codes, I found this code works well.  But not sure the overturning `sfT` is correct.

Thanks for your kind help. @jbusecke
