### ISSUE TITLE
[BUG] xgcm installed but can't be import 

### ISSUE THREAD

**Issue by AnnjoRo** [xgcm/xgcm#434]
**What happened**:
I installed the xgcm Librairie but once I tried to import it to use it, I obtain an error message, which is nowhere to be found on the internet.

**What you expected to happen**:
By using this same method on another mac (more recent), xgcm was nicely imported and ready to be used...

**Minimal Complete Verifiable Example**:

```python
! pip install xgcm
Requirement already satisfied: xgcm in ./opt/anaconda3/lib/python3.7/site-packages (0.6.2rc2.dev5+g09c50fd)
Requirement already satisfied: future in ./opt/anaconda3/lib/python3.7/site-packages (from xgcm) (0.17.1)
Requirement already satisfied: dask in ./opt/anaconda3/lib/python3.7/site-packages (from xgcm) (2.5.2)
Requirement already satisfied: xarray>=0.17.0 in ./opt/anaconda3/lib/python3.7/site-packages (from xgcm) (0.20.2)
Requirement already satisfied: numpy in ./opt/anaconda3/lib/python3.7/site-packages (from xgcm) (1.20.3)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in ./opt/anaconda3/lib/python3.7/site-packages (from xarray>=0.17.0->xgcm) (0.23)
Requirement already satisfied: pandas>=1.1 in ./opt/anaconda3/lib/python3.7/site-packages (from xarray>=0.17.0->xgcm) (1.3.5)
Requirement already satisfied: typing-extensions>=3.7; python_version < "3.8" in ./opt/anaconda3/lib/python3.7/site-packages (from xarray>=0.17.0->xgcm) (4.1.1)
Requirement already satisfied: zipp>=0.5 in ./opt/anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->xarray>=0.17.0->xgcm) (0.6.0)
Requirement already satisfied: python-dateutil>=2.7.3 in ./opt/anaconda3/lib/python3.7/site-packages (from pandas>=1.1->xarray>=0.17.0->xgcm) (2.8.0)
Requirement already satisfied: pytz>=2017.3 in ./opt/anaconda3/lib/python3.7/site-packages (from pandas>=1.1->xarray>=0.17.0->xgcm) (2019.3)
Requirement already satisfied: more-itertools in ./opt/anaconda3/lib/python3.7/site-packages (from zipp>=0.5->importlib-metadata; python_version < "3.8"->xarray>=0.17.0->xgcm) (7.2.0)
Requirement already satisfied: six>=1.5 in ./opt/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=1.1->xarray>=0.17.0->xgcm) (1.12.0)

import xgcm
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-814b32b375aa> in <module>
----> 1 import xgcm

~/opt/anaconda3/lib/python3.7/site-packages/xgcm/__init__.py in <module>
      4     __version__ = "unknown"
      5 
----> 6 from .autogenerate import generate_grid_ds
      7 from .grid import Axis, Grid

~/opt/anaconda3/lib/python3.7/site-packages/xgcm/autogenerate.py in <module>
----> 1 import xarray as xr
      2 
      3 from xgcm.grid import Axis, raw_interp_function
      4 
      5 

~/opt/anaconda3/lib/python3.7/site-packages/xarray/__init__.py in <module>
      1 import pkg_resources
      2 
----> 3 from . import testing, tutorial, ufuncs
      4 from .backends.api import (
      5     load_dataarray,

~/opt/anaconda3/lib/python3.7/site-packages/xarray/testing.py in <module>
      6 import numpy as np
      7 
----> 8 from xarray.core import duck_array_ops, formatting, utils
      9 from xarray.core.dataarray import DataArray
     10 from xarray.core.dataset import Dataset

~/opt/anaconda3/lib/python3.7/site-packages/xarray/core/duck_array_ops.py in <module>
     11 
     12 import numpy as np
---> 13 import pandas as pd
     14 
     15 from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils

~/opt/anaconda3/lib/python3.7/site-packages/pandas/__init__.py in <module>
     53 import pandas.core.config_init
     54 
---> 55 from pandas.core.api import (
     56     # dtype
     57     Int8Dtype,

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/api.py in <module>
      3 import numpy as np
      4 
----> 5 from pandas.core.arrays.integer import (
      6     Int8Dtype,
      7     Int16Dtype,

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/arrays/__init__.py in <module>
      8 from .datetimes import DatetimeArray  # noqa: F401
      9 from .integer import IntegerArray, integer_array  # noqa: F401
---> 10 from .interval import IntervalArray  # noqa: F401
     11 from .numpy_ import PandasArray, PandasDtype  # noqa: F401
     12 from .period import PeriodArray, period_array  # noqa: F401

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/arrays/interval.py in <module>
     36 from pandas.core.arrays.categorical import Categorical
     37 import pandas.core.common as com
---> 38 from pandas.core.indexes.base import Index, ensure_index
     39 
     40 _VALID_CLOSED = {"left", "right", "both", "neither"}

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py in <module>
     72 from pandas.core.ops import get_op_result_name, make_invalid_op
     73 import pandas.core.sorting as sorting
---> 74 from pandas.core.strings import StringMethods
     75 
     76 from pandas.io.formats.printing import (

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/strings/__init__.py in <module>
     28 #     - ArrowStringArray
     29 
---> 30 from pandas.core.strings.accessor import StringMethods
     31 from pandas.core.strings.base import BaseStringArrayMethods
     32 

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/strings/accessor.py in <module>
     14 
     15 import pandas._libs.lib as lib
---> 16 from pandas._typing import (
     17     DtypeObj,
     18     FrameOrSeriesUnion,

ImportError: cannot import name 'DtypeObj' from 'pandas._typing' (/Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/pandas/_typing.py)
```

**Anything else we need to know?**:
We are two to have that kind of issues, both of us having Mac book from 2013 and 2011. No idea if it's linked , but what's the odd
**xgcm version and environment**:

<details>

</details>

**Comment by rabernat** [comment]
Can you `import pandas`? If not, your problem has nothing to do with xgcm. The problem is with pandas.

This stackoverflow issue seems very similar. (I found it by just typing `ImportError: cannot import name 'DtypeObj' from 'pandas._typing'` into google.) https://stackoverflow.com/questions/68463220/pandas-importing-error-importerror-cannot-import-name-dtypearg-from-pandas

In general, we recommend installing scientific python packages (including xgcm) with conda, not pip.

**Comment by AnnjoRo** [comment]
oh, okey... pandas is not working... last time it was... sorry about that 

I also tried conda actually. I will try to fix the pandas issue then, thanks a lot

**Comment by AnnjoRo** [comment]
okey, so pandas is fixed, but still can't managed to import xgcm : 

```python
import pandas

import xgcm
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-2-814b32b375aa> in <module>
----> 1 import xgcm

~/opt/anaconda3/lib/python3.7/site-packages/xgcm/__init__.py in <module>
      4     __version__ = "unknown"
      5 
----> 6 from .autogenerate import generate_grid_ds
      7 from .grid import Axis, Grid

~/opt/anaconda3/lib/python3.7/site-packages/xgcm/autogenerate.py in <module>
      1 import xarray as xr
      2 
----> 3 from xgcm.grid import Axis, raw_interp_function
      4 
      5 

~/opt/anaconda3/lib/python3.7/site-packages/xgcm/grid.py in <module>
     15     import numba
     16 
---> 17     from .transform import conservative_interpolation, linear_interpolation
     18 except ImportError:
     19     numba = None

~/opt/anaconda3/lib/python3.7/site-packages/xgcm/transform.py in <module>
     17     ],
     18     "(n),(n),(m),(),()->(m)",
---> 19     nopython=True,
     20 )
     21 def _interp_1d_linear(

~/opt/anaconda3/lib/python3.7/site-packages/numba/npyufunc/decorators.py in wrap(func)
    177         guvec = GUVectorize(func, signature, **kws)
    178         for fty in ftylist:
--> 179             guvec.add(fty)
    180         return guvec.build_ufunc()
    181 

~/opt/anaconda3/lib/python3.7/site-packages/numba/npyufunc/ufuncbuilder.py in add(self, sig)
    194             targetoptions = self.nb_func.targetoptions
    195         cres, args, return_type = _compile_element_wise_function(
--> 196             self.nb_func, targetoptions, sig)
    197         sig = self._finalize_signature(cres, args, return_type)
    198         self._sigs.append(sig)

~/opt/anaconda3/lib/python3.7/site-packages/numba/npyufunc/ufuncbuilder.py in _compile_element_wise_function(nb_func, targetoptions, sig)
    128     # Do compilation
    129     # Return CompileResult to test
--> 130     cres = nb_func.compile(sig, **targetoptions)
    131     args, return_type = sigutils.normalize_signature(sig)
    132     return cres, args, return_type

~/opt/anaconda3/lib/python3.7/site-packages/numba/npyufunc/ufuncbuilder.py in compile(self, sig, locals, **targetoptions)
     77         flags.unset("enable_looplift")
     78 
---> 79         return self._compile_core(sig, flags, locals)
     80 
     81     def _compile_core(self, sig, flags, locals):

~/opt/anaconda3/lib/python3.7/site-packages/numba/npyufunc/ufuncbuilder.py in _compile_core(self, sig, flags, locals)
    112                                               self.py_func, args=args,
    113                                               return_type=return_type,
--> 114                                               flags=flags, locals=locals)
    115 
    116                 # cache lookup failed before so safe to save

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    970     pipeline = pipeline_class(typingctx, targetctx, library,
    971                               args, return_type, flags, locals)
--> 972     return pipeline.compile_extra(func)
    973 
    974 

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in compile_extra(self, func)
    388         self.lifted = ()
    389         self.lifted_from = None
--> 390         return self._compile_bytecode()
    391 
    392     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _compile_bytecode(self)
    901         """
    902         assert self.func_ir is None
--> 903         return self._compile_core()
    904 
    905     def _compile_ir(self):

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _compile_core(self)
    888         self.define_pipelines(pm)
    889         pm.finalize()
--> 890         res = pm.run(self.status)
    891         if res is not None:
    892             # Early pipeline completion

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    264                     # No more fallback pipelines?
    265                     if is_final_pipeline:
--> 266                         raise patched_exception
    267                     # Go to next fallback pipeline
    268                     else:

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    255                 try:
    256                     event("-- %s" % stage_name)
--> 257                     stage()
    258                 except _EarlyPipelineCompletion as e:
    259                     return e.result

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in stage_nopython_frontend(self)
    513                 self.args,
    514                 self.return_type,
--> 515                 self.locals)
    516             self.typemap = typemap
    517             self.return_type = return_type

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in type_inference_stage(typingctx, interp, args, return_type, locals)
   1122 
   1123         infer.build_constraint()
-> 1124         infer.propagate()
   1125         typemap, restype, calltypes = infer.unify()
   1126 

~/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py in propagate(self, raise_errors)
    925         if errors:
    926             if raise_errors:
--> 927                 raise errors[0]
    928             else:
    929                 return errors

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function interp at 0x119cd54d0>) with argument(s) of type(s): (array(float32, 1d, A), array(float32, 1d, A), array(float32, 1d, A))
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function np_interp_impl_inner_factory.<locals>.impl at 0x82d1d9200>) with argument(s) of type(s): (array(float32, 1d, A), array(float32, 1d, A), array(float32, 1d, A), dtype(float64))
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'slopes', defined at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2120)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2120:
    def impl(x, xp, fp, dtype):
        <source elided>
            if lenxp <= lenx:
                slopes = (dy[1:] - dy[:-1]) / (dx[1:] - dx[:-1])
                ^

[1] During: typing of assignment at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2122)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2122:
    def impl(x, xp, fp, dtype):
        <source elided>
            else:
                slopes = np.empty(0, dtype=dtype)
                ^

    raised from /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py:927
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'slopes', defined at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2120)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2120:
    def impl(x, xp, fp, dtype):
        <source elided>
            if lenxp <= lenx:
                slopes = (dy[1:] - dy[:-1]) / (dx[1:] - dx[:-1])
                ^

[1] During: typing of assignment at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2122)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2122:
    def impl(x, xp, fp, dtype):
        <source elided>
            else:
                slopes = np.empty(0, dtype=dtype)
                ^

    raised from /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py:927
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function np_interp_impl_inner_factory.<locals>.impl at 0x82d1d9200>)
[2] During: typing of call at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2237)


File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2237:
        def np_interp_impl(x, xp, fp):
            return inner(x, xp, fp, dtype)
            ^

    raised from /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py:927
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function np_interp_impl_inner_factory.<locals>.impl at 0x82d1d9200>) with argument(s) of type(s): (array(float32, 1d, A), array(float32, 1d, A), array(float32, 1d, A), dtype(float64))
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'slopes', defined at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2120)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2120:
    def impl(x, xp, fp, dtype):
        <source elided>
            if lenxp <= lenx:
                slopes = (dy[1:] - dy[:-1]) / (dx[1:] - dx[:-1])
                ^

[1] During: typing of assignment at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2122)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2122:
    def impl(x, xp, fp, dtype):
        <source elided>
            else:
                slopes = np.empty(0, dtype=dtype)
                ^

    raised from /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py:927
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'slopes', defined at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2120)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2120:
    def impl(x, xp, fp, dtype):
        <source elided>
            if lenxp <= lenx:
                slopes = (dy[1:] - dy[:-1]) / (dx[1:] - dx[:-1])
                ^

[1] During: typing of assignment at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2122)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2122:
    def impl(x, xp, fp, dtype):
        <source elided>
            else:
                slopes = np.empty(0, dtype=dtype)
                ^

    raised from /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py:927
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function np_interp_impl_inner_factory.<locals>.impl at 0x82d1d9200>)
[2] During: typing of call at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2237)


File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2237:
        def np_interp_impl(x, xp, fp):
            return inner(x, xp, fp, dtype)
            ^

    raised from /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py:927
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function interp at 0x119cd54d0>)
[2] During: typing of call at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/xgcm/transform.py (31)


File "opt/anaconda3/lib/python3.7/site-packages/xgcm/transform.py", line 31:
def _interp_1d_linear(
    <source elided>

    output[:] = np.interp(target_theta_levels, theta, phi)
    ^
```

**Comment by TomNicholas** [comment]
It seems to be erroring inside numba, which is weird. numba is supposed to be an optional dependency (and our core-deps CI environment manages to import xgcm without numba), but I would be interested to know if installing numba makes your error disappear or not?

**Comment by AnnjoRo** [comment]
Okey, so I tried to instal numba, but still the same error 

```python
import xgcm
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-1-814b32b375aa> in <module>
----> 1 import xgcm

~/opt/anaconda3/lib/python3.7/site-packages/xgcm/__init__.py in <module>
      4     __version__ = "unknown"
      5 
----> 6 from .autogenerate import generate_grid_ds
      7 from .grid import Axis, Grid

~/opt/anaconda3/lib/python3.7/site-packages/xgcm/autogenerate.py in <module>
      1 import xarray as xr
      2 
----> 3 from xgcm.grid import Axis, raw_interp_function
      4 
      5 

~/opt/anaconda3/lib/python3.7/site-packages/xgcm/grid.py in <module>
     15     import numba
     16 
---> 17     from .transform import conservative_interpolation, linear_interpolation
     18 except ImportError:
     19     numba = None

~/opt/anaconda3/lib/python3.7/site-packages/xgcm/transform.py in <module>
     17     ],
     18     "(n),(n),(m),(),()->(m)",
---> 19     nopython=True,
     20 )
     21 def _interp_1d_linear(

~/opt/anaconda3/lib/python3.7/site-packages/numba/npyufunc/decorators.py in wrap(func)
    177         guvec = GUVectorize(func, signature, **kws)
    178         for fty in ftylist:
--> 179             guvec.add(fty)
    180         return guvec.build_ufunc()
    181 

~/opt/anaconda3/lib/python3.7/site-packages/numba/npyufunc/ufuncbuilder.py in add(self, sig)
    194             targetoptions = self.nb_func.targetoptions
    195         cres, args, return_type = _compile_element_wise_function(
--> 196             self.nb_func, targetoptions, sig)
    197         sig = self._finalize_signature(cres, args, return_type)
    198         self._sigs.append(sig)

~/opt/anaconda3/lib/python3.7/site-packages/numba/npyufunc/ufuncbuilder.py in _compile_element_wise_function(nb_func, targetoptions, sig)
    128     # Do compilation
    129     # Return CompileResult to test
--> 130     cres = nb_func.compile(sig, **targetoptions)
    131     args, return_type = sigutils.normalize_signature(sig)
    132     return cres, args, return_type

~/opt/anaconda3/lib/python3.7/site-packages/numba/npyufunc/ufuncbuilder.py in compile(self, sig, locals, **targetoptions)
     77         flags.unset("enable_looplift")
     78 
---> 79         return self._compile_core(sig, flags, locals)
     80 
     81     def _compile_core(self, sig, flags, locals):

~/opt/anaconda3/lib/python3.7/site-packages/numba/npyufunc/ufuncbuilder.py in _compile_core(self, sig, flags, locals)
    112                                               self.py_func, args=args,
    113                                               return_type=return_type,
--> 114                                               flags=flags, locals=locals)
    115 
    116                 # cache lookup failed before so safe to save

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    970     pipeline = pipeline_class(typingctx, targetctx, library,
    971                               args, return_type, flags, locals)
--> 972     return pipeline.compile_extra(func)
    973 
    974 

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in compile_extra(self, func)
    388         self.lifted = ()
    389         self.lifted_from = None
--> 390         return self._compile_bytecode()
    391 
    392     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _compile_bytecode(self)
    901         """
    902         assert self.func_ir is None
--> 903         return self._compile_core()
    904 
    905     def _compile_ir(self):

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _compile_core(self)
    888         self.define_pipelines(pm)
    889         pm.finalize()
--> 890         res = pm.run(self.status)
    891         if res is not None:
    892             # Early pipeline completion

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    264                     # No more fallback pipelines?
    265                     if is_final_pipeline:
--> 266                         raise patched_exception
    267                     # Go to next fallback pipeline
    268                     else:

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    255                 try:
    256                     event("-- %s" % stage_name)
--> 257                     stage()
    258                 except _EarlyPipelineCompletion as e:
    259                     return e.result

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in stage_nopython_frontend(self)
    513                 self.args,
    514                 self.return_type,
--> 515                 self.locals)
    516             self.typemap = typemap
    517             self.return_type = return_type

~/opt/anaconda3/lib/python3.7/site-packages/numba/compiler.py in type_inference_stage(typingctx, interp, args, return_type, locals)
   1122 
   1123         infer.build_constraint()
-> 1124         infer.propagate()
   1125         typemap, restype, calltypes = infer.unify()
   1126 

~/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py in propagate(self, raise_errors)
    925         if errors:
    926             if raise_errors:
--> 927                 raise errors[0]
    928             else:
    929                 return errors

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function interp at 0x1083be200>) with argument(s) of type(s): (array(float32, 1d, A), array(float32, 1d, A), array(float32, 1d, A))
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function np_interp_impl_inner_factory.<locals>.impl at 0x8234f3170>) with argument(s) of type(s): (array(float32, 1d, A), array(float32, 1d, A), array(float32, 1d, A), dtype(float64))
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'slopes', defined at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2120)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2120:
    def impl(x, xp, fp, dtype):
        <source elided>
            if lenxp <= lenx:
                slopes = (dy[1:] - dy[:-1]) / (dx[1:] - dx[:-1])
                ^

[1] During: typing of assignment at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2122)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2122:
    def impl(x, xp, fp, dtype):
        <source elided>
            else:
                slopes = np.empty(0, dtype=dtype)
                ^

    raised from /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py:927
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'slopes', defined at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2120)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2120:
    def impl(x, xp, fp, dtype):
        <source elided>
            if lenxp <= lenx:
                slopes = (dy[1:] - dy[:-1]) / (dx[1:] - dx[:-1])
                ^

[1] During: typing of assignment at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2122)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2122:
    def impl(x, xp, fp, dtype):
        <source elided>
            else:
                slopes = np.empty(0, dtype=dtype)
                ^

    raised from /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py:927
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function np_interp_impl_inner_factory.<locals>.impl at 0x8234f3170>)
[2] During: typing of call at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2237)


File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2237:
        def np_interp_impl(x, xp, fp):
            return inner(x, xp, fp, dtype)
            ^

    raised from /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py:927
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function np_interp_impl_inner_factory.<locals>.impl at 0x8234f3170>) with argument(s) of type(s): (array(float32, 1d, A), array(float32, 1d, A), array(float32, 1d, A), dtype(float64))
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'slopes', defined at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2120)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2120:
    def impl(x, xp, fp, dtype):
        <source elided>
            if lenxp <= lenx:
                slopes = (dy[1:] - dy[:-1]) / (dx[1:] - dx[:-1])
                ^

[1] During: typing of assignment at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2122)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2122:
    def impl(x, xp, fp, dtype):
        <source elided>
            else:
                slopes = np.empty(0, dtype=dtype)
                ^

    raised from /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py:927
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'slopes', defined at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2120)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2120:
    def impl(x, xp, fp, dtype):
        <source elided>
            if lenxp <= lenx:
                slopes = (dy[1:] - dy[:-1]) / (dx[1:] - dx[:-1])
                ^

[1] During: typing of assignment at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2122)

File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2122:
    def impl(x, xp, fp, dtype):
        <source elided>
            else:
                slopes = np.empty(0, dtype=dtype)
                ^

    raised from /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py:927
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function np_interp_impl_inner_factory.<locals>.impl at 0x8234f3170>)
[2] During: typing of call at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py (2237)


File "opt/anaconda3/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2237:
        def np_interp_impl(x, xp, fp):
            return inner(x, xp, fp, dtype)
            ^

    raised from /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py:927
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function interp at 0x1083be200>)
[2] During: typing of call at /Users/pitbull/opt/anaconda3/lib/python3.7/site-packages/xgcm/transform.py (31)


File "opt/anaconda3/lib/python3.7/site-packages/xgcm/transform.py", line 31:
def _interp_1d_linear(
    <source elided>

    output[:] = np.interp(target_theta_levels, theta, phi)
    ^
````

but I created a next environment and no idea why it's working... 
But I'm still open to fixed this issue, if you are curious about it^^

**Comment by TomNicholas** [comment]
> but I created a next environment and no idea why it's working...

You opened a new environment and now it's working? That implies it's a problem with your local environment setup, not with xgcm. If you would like any further help we would really need to be able to reproduce your exact environment locally, and by far the easiest way to do that would be for you to use conda.

**Comment by AnnjoRo** [comment]
And thanks to @Marioherreroglez for recommending me to create a new environment
