### ISSUE TITLE
[BUG] Why am I able to install xgcm v0.7.0 with python 3.8?

### ISSUE THREAD

**Issue by malmans2** [xgcm/xgcm#494]
**What happened**:
I believe `xgcm>=0.7` is not compatible with `python<3.9`, but I'm able to install the latest `xgcm` with `python=3.8`

**What you expected to happen**:
Trying to install `xgcm` with unsupported dependencies should raise an error

**Minimal Complete Verifiable Example**:
```
mamba create -n test -c conda-forge python=3.8 xgcm=0.7
mamba activate test
python -c "import xgcm"
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mattia/MyGit/xgcm/xgcm/__init__.py", line 6, in <module>
    from .autogenerate import generate_grid_ds
  File "/Users/mattia/MyGit/xgcm/xgcm/autogenerate.py", line 3, in <module>
    from xgcm.grid import Axis, raw_interp_function
  File "/Users/mattia/MyGit/xgcm/xgcm/grid.py", line 12, in <module>
    from . import comodo, gridops
  File "/Users/mattia/MyGit/xgcm/xgcm/gridops.py", line 28, in <module>
    def diff_center_to_left(a):
  File "/Users/mattia/MyGit/xgcm/xgcm/grid_ufunc.py", line 548, in _as_grid_ufunc
    return GridUFunc(
  File "/Users/mattia/MyGit/xgcm/xgcm/grid_ufunc.py", line 395, in __init__
    self.signature = self._get_signature_from_str_or_type_hints(ufunc, str_sig)
  File "/Users/mattia/MyGit/xgcm/xgcm/grid_ufunc.py", line 413, in _get_signature_from_str_or_type_hints
    hints = get_type_hints(ufunc, include_extras=True)
TypeError: get_type_hints() got an unexpected keyword argument 'include_extras'
```

**Anything else we need to know?**:

**xgcm version and environment**:

<details>

```
# packages in environment at /Users/mattia/mambaforge/envs/test:
#
# Name                    Version                   Build  Channel
bokeh                     2.4.2            py38h50d1736_1    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
click                     8.1.3            py38h50d1736_0    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2           py38hed1de0f_2    conda-forge
dask                      2022.3.0           pyhd8ed1ab_1    conda-forge
dask-core                 2022.3.0           pyhd8ed1ab_0    conda-forge
distributed               2022.3.0           pyhd8ed1ab_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
fsspec                    2022.3.0           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py38h50d1736_5    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
importlib-metadata        4.11.3           py38h50d1736_1    conda-forge
importlib_metadata        4.11.3               hd8ed1ab_1    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jinja2                    3.1.1              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h5eb16cf_1    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libblas                   3.9.0           14_osx64_openblas    conda-forge
libcblas                  3.9.0           14_osx64_openblas    conda-forge
libcxx                    13.0.1               hc203e6f_0    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           14_osx64_openblas    conda-forge
libopenblas               0.3.20          openmp_hb3cd9ec_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libtiff                   4.3.0                h17f2ce3_3    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libzlib                   1.2.11            h6c3fc93_1014    conda-forge
llvm-openmp               14.0.3               ha654fa7_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.0.0            py38ha9ff022_1    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
markupsafe                2.1.1            py38hed1de0f_1    conda-forge
msgpack-python            1.0.3            py38h8b7791e_1    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
numpy                     1.22.3           py38h7eae8df_2    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   3.0.2                h6c3fc93_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.2            py38hb872667_1    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pillow                    9.1.0            py38h7207f37_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
psutil                    5.9.0            py38hed1de0f_1    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
python                    3.8.13          h66c20e1_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py38hed1de0f_4    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
setuptools                62.1.0           py38h50d1736_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.38.3               hd9f0692_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38hed1de0f_3    conda-forge
typing_extensions         4.2.0              pyha770c72_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xarray                    2022.3.0           pyhd8ed1ab_0    conda-forge
xgcm                      0.7.0              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h6c3fc93_1014    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge
```
</details>

**Comment by jbusecke** [comment]
Thanks for bringing this up @malmans2. It seems from your version that conda/mamba is not grabbing the updated build for 0.7.0 (yours says: `pyhd8ed1ab_0` while [`pyhd8ed1ab_0`](https://anaconda.org/conda-forge/xgcm/files) is available. Ill open an issue on the feedstock and try to track down the problem there.

**Comment by jbusecke** [comment]
See https://github.com/conda-forge/xgcm-feedstock/issues/14

**Comment by jbusecke** [comment]
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/259#event-6581278409 was just merged. Could you see if the problem has been resolved?

**Comment by malmans2** [comment]
Yes, I'm now getting the expected error:
```
Encountered problems while solving:
  - package xgcm-0.7.0-pyhd8ed1ab_0 requires python >=3.9, but none of the providers can be installed
```

**Comment by jbusecke** [comment]
Awesome. Thanks again for bringing this to our attention.
